### ISSUE TITLE
Lode Runner (ldrun) error with hi scores

### ISSUE THREAD

**Issue by ckeech** [GreatStoneEx/hi2txt-xml#30]
Hi there,

Thanks so much for this app! I'm using it with Launchbox and I love the fun of being able to have high score leaderboards. 
I've had a few hi scores with Lode Runner before (ldrun.zip) and so have other players. All of a sudden when I get a new high score it doesn't work. I worked out how to use hi2text by itself (thanks for the example .bat) and I get the same issue. 

The error is:

`hi2txt@1.12@20200502-CSharp\hi2txt_doc\example>call hi2txt.exe -r ldrun.hi
ERROR: Wrong ROUND value (0x0D) encoding detected: it can be due to a temporary corrupted .hi or nvram file   `

To attempt to resolve it I have:
- updated romset in case there was something changed
- updated MAME 0.238
- posted in Launchbox forums as I assumed it was specific to Launchbox (https://forums.launchbox-app.com/topic/54483-troubleshooting-mame-high-scores/?do=findComment&comment=397589)
- downloaded hi2text standalone in case it was a newer version and used my .hi file, same error
- deleted the .hi file and got a new high score so it was re-created, same issue

I suspect something has changed with how the .hi is formatted but I'm not sure. Any assistance would be greatly appreciated. Thanks again.

Here is the offending .hi file :) :
[ldrun.zip](https://github.com/GreatStoneEx/hi2txt-xml/files/7678581/ldrun.zip)

**Comment by GreatStoneEx** [comment]
Hello ckeech,

Thanks for the test-case and problem description! It helped a lot to fix the issue.
It was related to the "ROUND" information associated to each hiscore entry: it was decoded using base 10 instead of base 16, and the related check to ensure data integrity was failing when the player has reached the level 10 or better.
I have submitted a new version of ldrun.xml and ldrun4.xml here.

Do not hesitate to report issues or suggest new games to support (or even propose new xml for unsupported games :) ) !
Best regards

**Comment by ckeech** [comment]
Thank you so much! You're amazing.
